version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: freenstagram
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: freenstagram_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: freenstagram
      DB_PASSWORD: secret
      DB_NAME: freenstagram_db
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/root/uploads

volumes:
  db_data:
